org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.234
loader_version_range=[1,)

mod_id=emi_highlights_plus
mod_name=EMI Highlights Plus
mod_license=MIT
mod_version=0.2.0
mod_group_id=dev.circlestar.emihighlightsplus

emi_project_id=580555
emi_file_id=8081408
sophisticated_core_project_id=618298
sophisticated_core_file_id=8319586
sophisticated_storage_project_id=619320
sophisticated_storage_file_id=8318974
sophisticated_backpacks_project_id=422301
sophisticated_backpacks_file_id=8319596
projecte_project_id=226410
projecte_file_id=6611984
project_expansion_project_id=579177
project_expansion_file_id=7641689
ae2_project_id=223794
ae2_file_id=7027323
refined_storage_project_id=243076
refined_storage_file_id=8211701
