modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
config="emi_highlights_plus.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="CIRCLESTAR523"
description="""
Client-side compatibility layer for EMI Recipe Tree crafting-mode highlights
and logical inventories in custom storage screens.
"""

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="emi"
type="required"
versionRange="[1.1.24,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="sophisticatedcore"
type="optional"
versionRange="[1.4.60,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="sophisticatedstorage"
type="optional"
versionRange="[1.5.63,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="sophisticatedbackpacks"
type="optional"
versionRange="[3.25.64,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="projectexpansion"
type="optional"
versionRange="[1.21.1-1.0.6,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="projecte"
type="optional"
versionRange="[1.1.0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="ae2"
type="optional"
versionRange="[19.2.17,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="refinedstorage"
type="optional"
versionRange="[2.0.9,)"
ordering="AFTER"
side="CLIENT"
